version: "3.8"

services:
  service1:
    build:
      context: ./api/using-gpu
    image: api_using_gpu
    mem_limit: 10g
    ports:
      - "5000:5000"

  service2:
    build:
      context: ./website
    image: website_using_gpu
    ports:
      - "3000:3000"
